name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  maven-status:
    description: "Maven Status"
    value: ${{ steps.maven-build.outputs.status }}
runs:
  using: "composite"
  steps: 
  - name: Clone Repo hosting the composite action
    uses: actions/checkout@main
    with:
        repository: joshua-williamsOktana/compositeActionTest

  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
  - id: maven-build
    run: 
      status1="$(mvn -B package --file test/pom.xml)"
      status1="${status1//$'\n'/'%0A'}"
      status1="${status1//$'\r'/'%0D'}"
      status1="${status1//'%'/'%25'}"
      echo "::set-output name=status::$status1"
      
    shell: bash
