name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  maven-status:
    description: "Maven Status"
    value: ${{ steps.maven-build.outputs.status }}
runs:
  using: "composite"
  env:
      action_repo: ${{ github.action_repository }}
  env:
      action_branch:  ${{ github.action_ref }}
   - name: "Say Hello Mona it's Monday"
        run: echo "$action_repo $action_branch."
  steps: 
  - name: Clone Repo hosting the composite action
    uses: actions/checkout@v3
    with: 
        repository: $action_repo
        ref: $action_branch

  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
  - id: maven-build
    run: |
      MY_STRING=$(mvn -B package --file test/pom.xml)
      MY_STRING="${MY_STRING//'%'/'%25'}"
      MY_STRING="${MY_STRING//$'\n'/'%0A'}"
      MY_STRING="${MY_STRING//$'\r'/'%0D'}"
      echo "::set-output name=status::$(echo $MY_STRING)"
    
    shell: bash
