name: 'Hello World'
description: 'Greet someone'
inputs:
  action-repo:  # id of input
    description: 'The repo of the composite action'
    required: true
    default: ' '
  action-branch:  # id of input
    description: 'The branch of the repo that contains the composite action'
    required: true
    default: ' '
outputs:
  maven-status:
    description: "Maven Status"
    value: ${{ steps.maven-build.outputs.status }}


runs:
  using: "composite"
  
  
  steps: 
  - name: Clone Repo hosting the composite action
    uses: actions/checkout@v3
    with: 
        repository: ${{ inputs.action-repo }}
        ref: ${{ inputs.action-branch }}
  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
  - id: maven-build
    run: |
      MY_STRING=$(mvn -B package --file test/pom.xml)
      MY_STRING="${MY_STRING//'%'/'%25'}"
      MY_STRING="${MY_STRING//$'\n'/'%0A'}"
      MY_STRING="${MY_STRING//$'\r'/'%0D'}"
      echo "::set-output name=status::$(echo $MY_STRING)"
    
    shell: bash
