name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@main
      with:
        repository: joshua-williamsOktana/compositeActionTest
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash  
    - run: mvntest
      shell: bash
